# Generated by Django 5.0 on 2024-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_imagesproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
